# Generated by Django 2.0.6 on 2018-06-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
